name: Unit Tests

on:
  # pull_request: {}
  push: 
    branches-ignore:
      - gh-pages
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: build the binary
        run: |
          go build -mod vendor -o dist/provider ./cmd/server/main.go
      
      - name: Run Unit Tests
        run: |
          go test -covermode=count -coverprofile=profile.cov ./...
      
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GO111MODULE=off go get github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
